# Generated by Django 3.0.3 on 2020-02-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
    ]
