# Generated by Django 3.0.3 on 2020-02-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200224_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name_in_dir',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
